/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package opennlpdemo.test;

import java.io.FileInputStream;
import java.io.InputStream;
import opennlp.tools.namefind.NameFinderME;
import opennlp.tools.namefind.TokenNameFinderModel;
import opennlp.tools.util.Span;

/**
 * need to pass tokens generated by TokenizerDemo 
 * @author Ganesh Pachpind
 */
public class NameFinderDemo
{    
    public static Span[] findnames(String [] tokens)
    {
        Span [] spandata=null;
      try
       {
        InputStream is=new FileInputStream(Config.load().getProperty("modelpath")+"en-ner-person.bin");
        TokenNameFinderModel model=new TokenNameFinderModel(is);
        NameFinderME nameFinder=new NameFinderME(model);
        spandata = nameFinder.find(tokens);
       }
       catch(Exception e )
       {
            System.out.println(e.toString());
       }
      return spandata;
     }

    /**
     * use to print names 
     */
    public static void printnames(Span [] spandata,String[] tokens)
    {
        // return array of string
        String[] data=Span.spansToStrings(spandata, tokens);
        for(String s:data)
        {
            System.out.println(s.toString());
        }
    }
}
